### ISSUE TITLE
T430 Memory Frequency Bricks Board

### ISSUE THREAD

**Issue by TheGamingBarrel** [n4ru/1vyrain#24] opened 2020-02-04 15:58 UTC
After changing the memory frequency on my test T430 to 1066MHz I found that the board would refuse to boot ever again, removing the CMOS battery and main battery, power cycling it, absolutely nothing would work, I'm trying to see if I can flash coreboot via hardware to recover this board.

Note, had 8GB + 4GB of Samsung 1866MHz CL10 RAM Installed at the time, will not boot regardless of the RAM installed in any config.

**Comment by an94baller** [comment] 2020-02-04 20:12
I can confirm that the issue is valid, the only solution is to not use 1066 memory strap, this cannot be fixed by any soft resets as you mentioned.

Maybe as part of the bios modification we can hide 1066 strap or delete the ability for users to select it?

Source: had to borrow n4ru's RPI to unbrick mine (flashing stock bios backup)

**Comment by datNoko** [comment] 2020-02-04 20:13
As stated in the Readme "Worst case scenario, you can flash a backup or fresh BIOS using a hardware programmer." so i guess flashing it with hardware will work. If the memory in the bios was changed to 1066Mhz for a single channel then you got 2132 on dual channel. Maybe the memory cant handle it.

**Comment by an94baller** [comment] 2020-02-04 20:14
> 
> 
> As stated in the Readme "Worst case scenario, you can flash a backup or fresh BIOS using a hardware programmer." so i guess flashing it with hardware will work. **If the memory in the bios was changed to 1066Mhz for a single channel then you got 2132 on dual channel.** Maybe the memory cant handle it.

I don't think that's how it works

**Comment by n4ru** [comment] 2020-02-04 20:45
This is not an 1vyrain issue, but this is indeed now confirmed to brick. I have personally fixed another user's T430 by hardware flashing a BIOS backup (though you can also flash any patched 4MB BIOS, don't even need a backup).

I'll add a giant warning and add this to the list of things to add to the FAQ. Please be cautious with the advanced menu, but in my years of use I have not encountered any other brick like this.

**Comment by digmorepaka** [comment] 2020-02-10 22:42
Just for future reference, this is not an issue of the frequency limiter, but issue of the actual ram initialization. A user reported their machine not booting with 1066 dimms installed, and as expected with a 1333 dimm it did work correctly.

**Comment by an94baller** [comment] 2020-02-11 00:17
> 
> 
> Just for future reference, this is not an issue of the frequency limiter, but issue of the actual ram initialization. A user reported their machine not booting with 1066 dimms installed, and as expected with a 1333 dimm it did work correctly.

I put 2133 ram which works on my T430, setting to 1066 in memory limiter does brick the machine



I'm not sure why/how/what's wrong with 1066 strap being broken on these machines

**Comment by adrianparvino** [comment] 2020-02-15 14:41
I'm the user, just for reference.

**Comment by n4ru** [comment] 2020-02-21 05:34
Closing this now, the Long Form FAQ contains a warning to avoid this memory timing.

**Closed by n4ru** 2020-02-21 05:34 UTC
